/* automatically generated by rust-bindgen 0.72.0 */

use super::*;

pub struct Library {
    __library: ::libloading::Library,
    pub NVSDK_NGX_Parameter_SetULL: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_ulonglong,
    ),
    pub NVSDK_NGX_Parameter_SetF: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: f32,
    ),
    pub NVSDK_NGX_Parameter_SetD: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: f64,
    ),
    pub NVSDK_NGX_Parameter_SetUI: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_uint,
    ),
    pub NVSDK_NGX_Parameter_SetI: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_int,
    ),
    pub NVSDK_NGX_Parameter_SetVoidPointer: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: *mut ::std::os::raw::c_void,
    ),
    pub NVSDK_NGX_Parameter_GetULL: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_ulonglong,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_Parameter_GetF: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut f32,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_Parameter_GetD: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut f64,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_Parameter_GetUI: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_uint,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_Parameter_GetI: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_int,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_Parameter_GetVoidPointer: unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut *mut ::std::os::raw::c_void,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_RequiredExtensions: unsafe extern "C" fn(
        OutInstanceExtCount: *mut ::std::os::raw::c_uint,
        OutInstanceExts: *mut *mut *const ::std::os::raw::c_char,
        OutDeviceExtCount: *mut ::std::os::raw::c_uint,
        OutDeviceExts: *mut *mut *const ::std::os::raw::c_char,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_Init: unsafe extern "C" fn(
        InApplicationId: ::std::os::raw::c_ulonglong,
        InApplicationDataPath: *const wchar_t,
        InInstance: VkInstance,
        InPD: VkPhysicalDevice,
        InDevice: VkDevice,
        InGIPA: PFN_vkGetInstanceProcAddr,
        InGDPA: PFN_vkGetDeviceProcAddr,
        InFeatureInfo: *const NVSDK_NGX_FeatureCommonInfo,
        InSDKVersion: NVSDK_NGX_Version,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_Init_with_ProjectID: unsafe extern "C" fn(
        InProjectId: *const ::std::os::raw::c_char,
        InEngineType: NVSDK_NGX_EngineType,
        InEngineVersion: *const ::std::os::raw::c_char,
        InApplicationDataPath: *const wchar_t,
        InInstance: VkInstance,
        InPD: VkPhysicalDevice,
        InDevice: VkDevice,
        InGIPA: PFN_vkGetInstanceProcAddr,
        InGDPA: PFN_vkGetDeviceProcAddr,
        InFeatureInfo: *const NVSDK_NGX_FeatureCommonInfo,
        InSDKVersion: NVSDK_NGX_Version,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_Shutdown1: unsafe extern "C" fn(InDevice: VkDevice) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_AllocateParameters:
        unsafe extern "C" fn(OutParameters: *mut *mut NVSDK_NGX_Parameter) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_GetCapabilityParameters:
        unsafe extern "C" fn(OutParameters: *mut *mut NVSDK_NGX_Parameter) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_DestroyParameters:
        unsafe extern "C" fn(InParameters: *mut NVSDK_NGX_Parameter) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_GetScratchBufferSize: unsafe extern "C" fn(
        InFeatureId: NVSDK_NGX_Feature,
        InParameters: *const NVSDK_NGX_Parameter,
        OutSizeInBytes: *mut usize,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_CreateFeature: unsafe extern "C" fn(
        InCmdBuffer: VkCommandBuffer,
        InFeatureID: NVSDK_NGX_Feature,
        InParameters: *mut NVSDK_NGX_Parameter,
        OutHandle: *mut *mut NVSDK_NGX_Handle,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_CreateFeature1: unsafe extern "C" fn(
        InDevice: VkDevice,
        InCmdList: VkCommandBuffer,
        InFeatureID: NVSDK_NGX_Feature,
        InParameters: *mut NVSDK_NGX_Parameter,
        OutHandle: *mut *mut NVSDK_NGX_Handle,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_ReleaseFeature:
        unsafe extern "C" fn(InHandle: *mut NVSDK_NGX_Handle) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_GetFeatureRequirements: unsafe extern "C" fn(
        Instance: VkInstance,
        PhysicalDevice: VkPhysicalDevice,
        FeatureDiscoveryInfo: *const NVSDK_NGX_FeatureDiscoveryInfo,
        OutSupported: *mut NVSDK_NGX_FeatureRequirement,
    ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_GetFeatureInstanceExtensionRequirements:
        unsafe extern "C" fn(
            FeatureDiscoveryInfo: *const NVSDK_NGX_FeatureDiscoveryInfo,
            OutExtensionCount: *mut u32,
            OutExtensionProperties: *mut *mut VkExtensionProperties,
        ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_GetFeatureDeviceExtensionRequirements:
        unsafe extern "C" fn(
            Instance: VkInstance,
            PhysicalDevice: VkPhysicalDevice,
            FeatureDiscoveryInfo: *const NVSDK_NGX_FeatureDiscoveryInfo,
            OutExtensionCount: *mut u32,
            OutExtensionProperties: *mut *mut VkExtensionProperties,
        ) -> NVSDK_NGX_Result,
    pub NVSDK_NGX_VULKAN_EvaluateFeature_C: unsafe extern "C" fn(
        InCmdList: VkCommandBuffer,
        InFeatureHandle: *const NVSDK_NGX_Handle,
        InParameters: *const NVSDK_NGX_Parameter,
        InCallback: PFN_NVSDK_NGX_ProgressCallback_C,
    ) -> NVSDK_NGX_Result,
    pub GetNGXResultAsString: unsafe extern "C" fn(InNGXResult: NVSDK_NGX_Result) -> *const wchar_t,
    pub NVSDK_NGX_UpdateFeature: unsafe extern "C" fn(
        ApplicationId: *const NVSDK_NGX_Application_Identifier,
        FeatureID: NVSDK_NGX_Feature,
    ) -> NVSDK_NGX_Result,
}
impl Library {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let library = ::libloading::Library::new(path)?;
        Self::from_library(library)
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let NVSDK_NGX_Parameter_SetULL = __library
            .get(b"NVSDK_NGX_Parameter_SetULL\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_SetF = __library
            .get(b"NVSDK_NGX_Parameter_SetF\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_SetD = __library
            .get(b"NVSDK_NGX_Parameter_SetD\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_SetUI = __library
            .get(b"NVSDK_NGX_Parameter_SetUI\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_SetI = __library
            .get(b"NVSDK_NGX_Parameter_SetI\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_SetVoidPointer = __library
            .get(b"NVSDK_NGX_Parameter_SetVoidPointer\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_GetULL = __library
            .get(b"NVSDK_NGX_Parameter_GetULL\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_GetF = __library
            .get(b"NVSDK_NGX_Parameter_GetF\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_GetD = __library
            .get(b"NVSDK_NGX_Parameter_GetD\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_GetUI = __library
            .get(b"NVSDK_NGX_Parameter_GetUI\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_GetI = __library
            .get(b"NVSDK_NGX_Parameter_GetI\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_Parameter_GetVoidPointer = __library
            .get(b"NVSDK_NGX_Parameter_GetVoidPointer\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_RequiredExtensions = __library
            .get(b"NVSDK_NGX_VULKAN_RequiredExtensions\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_Init = __library.get(b"NVSDK_NGX_VULKAN_Init\0").map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_Init_with_ProjectID = __library
            .get(b"NVSDK_NGX_VULKAN_Init_with_ProjectID\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_Shutdown1 = __library
            .get(b"NVSDK_NGX_VULKAN_Shutdown1\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_AllocateParameters = __library
            .get(b"NVSDK_NGX_VULKAN_AllocateParameters\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_GetCapabilityParameters = __library
            .get(b"NVSDK_NGX_VULKAN_GetCapabilityParameters\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_DestroyParameters = __library
            .get(b"NVSDK_NGX_VULKAN_DestroyParameters\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_GetScratchBufferSize = __library
            .get(b"NVSDK_NGX_VULKAN_GetScratchBufferSize\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_CreateFeature = __library
            .get(b"NVSDK_NGX_VULKAN_CreateFeature\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_CreateFeature1 = __library
            .get(b"NVSDK_NGX_VULKAN_CreateFeature1\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_ReleaseFeature = __library
            .get(b"NVSDK_NGX_VULKAN_ReleaseFeature\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_GetFeatureRequirements = __library
            .get(b"NVSDK_NGX_VULKAN_GetFeatureRequirements\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_GetFeatureInstanceExtensionRequirements = __library
            .get(b"NVSDK_NGX_VULKAN_GetFeatureInstanceExtensionRequirements\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_GetFeatureDeviceExtensionRequirements = __library
            .get(b"NVSDK_NGX_VULKAN_GetFeatureDeviceExtensionRequirements\0")
            .map(|sym| *sym)?;
        let NVSDK_NGX_VULKAN_EvaluateFeature_C = __library
            .get(b"NVSDK_NGX_VULKAN_EvaluateFeature_C\0")
            .map(|sym| *sym)?;
        let GetNGXResultAsString = __library.get(b"GetNGXResultAsString\0").map(|sym| *sym)?;
        let NVSDK_NGX_UpdateFeature = __library
            .get(b"NVSDK_NGX_UpdateFeature\0")
            .map(|sym| *sym)?;
        Ok(Library {
            __library,
            NVSDK_NGX_Parameter_SetULL,
            NVSDK_NGX_Parameter_SetF,
            NVSDK_NGX_Parameter_SetD,
            NVSDK_NGX_Parameter_SetUI,
            NVSDK_NGX_Parameter_SetI,
            NVSDK_NGX_Parameter_SetVoidPointer,
            NVSDK_NGX_Parameter_GetULL,
            NVSDK_NGX_Parameter_GetF,
            NVSDK_NGX_Parameter_GetD,
            NVSDK_NGX_Parameter_GetUI,
            NVSDK_NGX_Parameter_GetI,
            NVSDK_NGX_Parameter_GetVoidPointer,
            NVSDK_NGX_VULKAN_RequiredExtensions,
            NVSDK_NGX_VULKAN_Init,
            NVSDK_NGX_VULKAN_Init_with_ProjectID,
            NVSDK_NGX_VULKAN_Shutdown1,
            NVSDK_NGX_VULKAN_AllocateParameters,
            NVSDK_NGX_VULKAN_GetCapabilityParameters,
            NVSDK_NGX_VULKAN_DestroyParameters,
            NVSDK_NGX_VULKAN_GetScratchBufferSize,
            NVSDK_NGX_VULKAN_CreateFeature,
            NVSDK_NGX_VULKAN_CreateFeature1,
            NVSDK_NGX_VULKAN_ReleaseFeature,
            NVSDK_NGX_VULKAN_GetFeatureRequirements,
            NVSDK_NGX_VULKAN_GetFeatureInstanceExtensionRequirements,
            NVSDK_NGX_VULKAN_GetFeatureDeviceExtensionRequirements,
            NVSDK_NGX_VULKAN_EvaluateFeature_C,
            GetNGXResultAsString,
            NVSDK_NGX_UpdateFeature,
        })
    }
    pub unsafe fn NVSDK_NGX_Parameter_SetULL(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_ulonglong,
    ) {
        (self.NVSDK_NGX_Parameter_SetULL)(InParameter, InName, InValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_SetF(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: f32,
    ) {
        (self.NVSDK_NGX_Parameter_SetF)(InParameter, InName, InValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_SetD(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: f64,
    ) {
        (self.NVSDK_NGX_Parameter_SetD)(InParameter, InName, InValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_SetUI(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_uint,
    ) {
        (self.NVSDK_NGX_Parameter_SetUI)(InParameter, InName, InValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_SetI(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_int,
    ) {
        (self.NVSDK_NGX_Parameter_SetI)(InParameter, InName, InValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_SetVoidPointer(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: *mut ::std::os::raw::c_void,
    ) {
        (self.NVSDK_NGX_Parameter_SetVoidPointer)(InParameter, InName, InValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_GetULL(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_ulonglong,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_Parameter_GetULL)(InParameter, InName, OutValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_GetF(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut f32,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_Parameter_GetF)(InParameter, InName, OutValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_GetD(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut f64,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_Parameter_GetD)(InParameter, InName, OutValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_GetUI(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_uint,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_Parameter_GetUI)(InParameter, InName, OutValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_GetI(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_int,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_Parameter_GetI)(InParameter, InName, OutValue)
    }
    pub unsafe fn NVSDK_NGX_Parameter_GetVoidPointer(
        &self,
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut *mut ::std::os::raw::c_void,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_Parameter_GetVoidPointer)(InParameter, InName, OutValue)
    }
    pub unsafe fn NVSDK_NGX_VULKAN_RequiredExtensions(
        &self,
        OutInstanceExtCount: *mut ::std::os::raw::c_uint,
        OutInstanceExts: *mut *mut *const ::std::os::raw::c_char,
        OutDeviceExtCount: *mut ::std::os::raw::c_uint,
        OutDeviceExts: *mut *mut *const ::std::os::raw::c_char,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_RequiredExtensions)(
            OutInstanceExtCount,
            OutInstanceExts,
            OutDeviceExtCount,
            OutDeviceExts,
        )
    }
    pub unsafe fn NVSDK_NGX_VULKAN_Init(
        &self,
        InApplicationId: ::std::os::raw::c_ulonglong,
        InApplicationDataPath: *const wchar_t,
        InInstance: VkInstance,
        InPD: VkPhysicalDevice,
        InDevice: VkDevice,
        InGIPA: PFN_vkGetInstanceProcAddr,
        InGDPA: PFN_vkGetDeviceProcAddr,
        InFeatureInfo: *const NVSDK_NGX_FeatureCommonInfo,
        InSDKVersion: NVSDK_NGX_Version,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_Init)(
            InApplicationId,
            InApplicationDataPath,
            InInstance,
            InPD,
            InDevice,
            InGIPA,
            InGDPA,
            InFeatureInfo,
            InSDKVersion,
        )
    }
    pub unsafe fn NVSDK_NGX_VULKAN_Init_with_ProjectID(
        &self,
        InProjectId: *const ::std::os::raw::c_char,
        InEngineType: NVSDK_NGX_EngineType,
        InEngineVersion: *const ::std::os::raw::c_char,
        InApplicationDataPath: *const wchar_t,
        InInstance: VkInstance,
        InPD: VkPhysicalDevice,
        InDevice: VkDevice,
        InGIPA: PFN_vkGetInstanceProcAddr,
        InGDPA: PFN_vkGetDeviceProcAddr,
        InFeatureInfo: *const NVSDK_NGX_FeatureCommonInfo,
        InSDKVersion: NVSDK_NGX_Version,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_Init_with_ProjectID)(
            InProjectId,
            InEngineType,
            InEngineVersion,
            InApplicationDataPath,
            InInstance,
            InPD,
            InDevice,
            InGIPA,
            InGDPA,
            InFeatureInfo,
            InSDKVersion,
        )
    }
    pub unsafe fn NVSDK_NGX_VULKAN_Shutdown1(&self, InDevice: VkDevice) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_Shutdown1)(InDevice)
    }
    pub unsafe fn NVSDK_NGX_VULKAN_AllocateParameters(
        &self,
        OutParameters: *mut *mut NVSDK_NGX_Parameter,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_AllocateParameters)(OutParameters)
    }
    pub unsafe fn NVSDK_NGX_VULKAN_GetCapabilityParameters(
        &self,
        OutParameters: *mut *mut NVSDK_NGX_Parameter,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_GetCapabilityParameters)(OutParameters)
    }
    pub unsafe fn NVSDK_NGX_VULKAN_DestroyParameters(
        &self,
        InParameters: *mut NVSDK_NGX_Parameter,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_DestroyParameters)(InParameters)
    }
    pub unsafe fn NVSDK_NGX_VULKAN_GetScratchBufferSize(
        &self,
        InFeatureId: NVSDK_NGX_Feature,
        InParameters: *const NVSDK_NGX_Parameter,
        OutSizeInBytes: *mut usize,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_GetScratchBufferSize)(InFeatureId, InParameters, OutSizeInBytes)
    }
    pub unsafe fn NVSDK_NGX_VULKAN_CreateFeature(
        &self,
        InCmdBuffer: VkCommandBuffer,
        InFeatureID: NVSDK_NGX_Feature,
        InParameters: *mut NVSDK_NGX_Parameter,
        OutHandle: *mut *mut NVSDK_NGX_Handle,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_CreateFeature)(InCmdBuffer, InFeatureID, InParameters, OutHandle)
    }
    pub unsafe fn NVSDK_NGX_VULKAN_CreateFeature1(
        &self,
        InDevice: VkDevice,
        InCmdList: VkCommandBuffer,
        InFeatureID: NVSDK_NGX_Feature,
        InParameters: *mut NVSDK_NGX_Parameter,
        OutHandle: *mut *mut NVSDK_NGX_Handle,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_CreateFeature1)(
            InDevice,
            InCmdList,
            InFeatureID,
            InParameters,
            OutHandle,
        )
    }
    pub unsafe fn NVSDK_NGX_VULKAN_ReleaseFeature(
        &self,
        InHandle: *mut NVSDK_NGX_Handle,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_ReleaseFeature)(InHandle)
    }
    pub unsafe fn NVSDK_NGX_VULKAN_GetFeatureRequirements(
        &self,
        Instance: VkInstance,
        PhysicalDevice: VkPhysicalDevice,
        FeatureDiscoveryInfo: *const NVSDK_NGX_FeatureDiscoveryInfo,
        OutSupported: *mut NVSDK_NGX_FeatureRequirement,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_GetFeatureRequirements)(
            Instance,
            PhysicalDevice,
            FeatureDiscoveryInfo,
            OutSupported,
        )
    }
    pub unsafe fn NVSDK_NGX_VULKAN_GetFeatureInstanceExtensionRequirements(
        &self,
        FeatureDiscoveryInfo: *const NVSDK_NGX_FeatureDiscoveryInfo,
        OutExtensionCount: *mut u32,
        OutExtensionProperties: *mut *mut VkExtensionProperties,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_GetFeatureInstanceExtensionRequirements)(
            FeatureDiscoveryInfo,
            OutExtensionCount,
            OutExtensionProperties,
        )
    }
    pub unsafe fn NVSDK_NGX_VULKAN_GetFeatureDeviceExtensionRequirements(
        &self,
        Instance: VkInstance,
        PhysicalDevice: VkPhysicalDevice,
        FeatureDiscoveryInfo: *const NVSDK_NGX_FeatureDiscoveryInfo,
        OutExtensionCount: *mut u32,
        OutExtensionProperties: *mut *mut VkExtensionProperties,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_GetFeatureDeviceExtensionRequirements)(
            Instance,
            PhysicalDevice,
            FeatureDiscoveryInfo,
            OutExtensionCount,
            OutExtensionProperties,
        )
    }
    pub unsafe fn NVSDK_NGX_VULKAN_EvaluateFeature_C(
        &self,
        InCmdList: VkCommandBuffer,
        InFeatureHandle: *const NVSDK_NGX_Handle,
        InParameters: *const NVSDK_NGX_Parameter,
        InCallback: PFN_NVSDK_NGX_ProgressCallback_C,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_VULKAN_EvaluateFeature_C)(
            InCmdList,
            InFeatureHandle,
            InParameters,
            InCallback,
        )
    }
    pub unsafe fn GetNGXResultAsString(&self, InNGXResult: NVSDK_NGX_Result) -> *const wchar_t {
        (self.GetNGXResultAsString)(InNGXResult)
    }
    pub unsafe fn NVSDK_NGX_UpdateFeature(
        &self,
        ApplicationId: *const NVSDK_NGX_Application_Identifier,
        FeatureID: NVSDK_NGX_Feature,
    ) -> NVSDK_NGX_Result {
        (self.NVSDK_NGX_UpdateFeature)(ApplicationId, FeatureID)
    }
}
