/* automatically generated by rust-bindgen 0.72.0 */

use super::*;

extern "C" {
    pub fn NVSDK_NGX_Parameter_SetULL(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_ulonglong,
    );
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetF(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: f32,
    );
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetD(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: f64,
    );
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetUI(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_uint,
    );
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetI(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetVoidPointer(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetULL(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_ulonglong,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetF(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut f32,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetD(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut f64,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetUI(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_uint,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetI(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_int,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetVoidPointer(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut *mut ::std::os::raw::c_void,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_RequiredExtensions(
        OutInstanceExtCount: *mut ::std::os::raw::c_uint,
        OutInstanceExts: *mut *mut *const ::std::os::raw::c_char,
        OutDeviceExtCount: *mut ::std::os::raw::c_uint,
        OutDeviceExts: *mut *mut *const ::std::os::raw::c_char,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_Init(
        InApplicationId: ::std::os::raw::c_ulonglong,
        InApplicationDataPath: *const wchar_t,
        InInstance: VkInstance,
        InPD: VkPhysicalDevice,
        InDevice: VkDevice,
        InGIPA: PFN_vkGetInstanceProcAddr,
        InGDPA: PFN_vkGetDeviceProcAddr,
        InFeatureInfo: *const NVSDK_NGX_FeatureCommonInfo,
        InSDKVersion: NVSDK_NGX_Version,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_Init_with_ProjectID(
        InProjectId: *const ::std::os::raw::c_char,
        InEngineType: NVSDK_NGX_EngineType,
        InEngineVersion: *const ::std::os::raw::c_char,
        InApplicationDataPath: *const wchar_t,
        InInstance: VkInstance,
        InPD: VkPhysicalDevice,
        InDevice: VkDevice,
        InGIPA: PFN_vkGetInstanceProcAddr,
        InGDPA: PFN_vkGetDeviceProcAddr,
        InFeatureInfo: *const NVSDK_NGX_FeatureCommonInfo,
        InSDKVersion: NVSDK_NGX_Version,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_Shutdown1(InDevice: VkDevice) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_AllocateParameters(
        OutParameters: *mut *mut NVSDK_NGX_Parameter,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_GetCapabilityParameters(
        OutParameters: *mut *mut NVSDK_NGX_Parameter,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_DestroyParameters(
        InParameters: *mut NVSDK_NGX_Parameter,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_GetScratchBufferSize(
        InFeatureId: NVSDK_NGX_Feature,
        InParameters: *const NVSDK_NGX_Parameter,
        OutSizeInBytes: *mut usize,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_CreateFeature(
        InCmdBuffer: VkCommandBuffer,
        InFeatureID: NVSDK_NGX_Feature,
        InParameters: *mut NVSDK_NGX_Parameter,
        OutHandle: *mut *mut NVSDK_NGX_Handle,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_CreateFeature1(
        InDevice: VkDevice,
        InCmdList: VkCommandBuffer,
        InFeatureID: NVSDK_NGX_Feature,
        InParameters: *mut NVSDK_NGX_Parameter,
        OutHandle: *mut *mut NVSDK_NGX_Handle,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_ReleaseFeature(InHandle: *mut NVSDK_NGX_Handle) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_GetFeatureRequirements(
        Instance: VkInstance,
        PhysicalDevice: VkPhysicalDevice,
        FeatureDiscoveryInfo: *const NVSDK_NGX_FeatureDiscoveryInfo,
        OutSupported: *mut NVSDK_NGX_FeatureRequirement,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_GetFeatureInstanceExtensionRequirements(
        FeatureDiscoveryInfo: *const NVSDK_NGX_FeatureDiscoveryInfo,
        OutExtensionCount: *mut u32,
        OutExtensionProperties: *mut *mut VkExtensionProperties,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_GetFeatureDeviceExtensionRequirements(
        Instance: VkInstance,
        PhysicalDevice: VkPhysicalDevice,
        FeatureDiscoveryInfo: *const NVSDK_NGX_FeatureDiscoveryInfo,
        OutExtensionCount: *mut u32,
        OutExtensionProperties: *mut *mut VkExtensionProperties,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn NVSDK_NGX_VULKAN_EvaluateFeature_C(
        InCmdList: VkCommandBuffer,
        InFeatureHandle: *const NVSDK_NGX_Handle,
        InParameters: *const NVSDK_NGX_Parameter,
        InCallback: PFN_NVSDK_NGX_ProgressCallback_C,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn GetNGXResultAsString(InNGXResult: NVSDK_NGX_Result) -> *const wchar_t;
}
extern "C" {
    pub fn NVSDK_NGX_UpdateFeature(
        ApplicationId: *const NVSDK_NGX_Application_Identifier,
        FeatureID: NVSDK_NGX_Feature,
    ) -> NVSDK_NGX_Result;
}
