name: CI

on: [push, pull_request]

env:
  minrust: 1.65.0

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        name:
          - stable
          - beta
          - nightly

        include:
          - name: beta
            toolchain: beta
          - name: nightly
            toolchain: nightly

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        id: tc
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain || 'stable' }}

      - name: Setup cache
        if: runner.os != 'macOS'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test-${{ steps.tc.outputs.cachekey }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Vulkan loader
        run: sudo apt-get install libvulkan-dev

      - name: Build all features
        if: matrix.features == ''
        run: cargo build --all-features

      - name: Test all features
        if: matrix.features == ''
        run: cargo test --all-features

      - name: Build with no default features
        if: matrix.features == ''
        run: cargo build --no-default-features

  clippy:
    name: Run clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        id: tc
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-clippy-${{ steps.tc.outputs.cachekey }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Vulkan loader
        run: sudo apt-get install libvulkan-dev

      - run: cargo clippy

  MSRV:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain (${{ env.minrust }})
        id: tc
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.minrust }}

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-msrv-${{ steps.tc.outputs.cachekey }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Vulkan loader
        run: sudo apt-get install libvulkan-dev

      - run: cargo check --all-features

  doc:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        id: tc
        uses: dtolnay/rust-toolchain@nightly

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-docs-${{ steps.tc.outputs.cachekey }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Vulkan loader
        run: sudo apt-get install libvulkan-dev

      - name: Build docs
        run: |
          cargo doc
