# Copied from Twilight's Lint workflow.
#
# https://github.com/twilight-rs/twilight/blob/trunk/.github/workflows/lint.yml
name: Lint

on: [push, pull_request]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        id: tc
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-clippy-rustc-${{ steps.tc.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Vulkan loader
        run: sudo apt-get install libvulkan-dev

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -Dwarnings

  rustfmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
